- name: Install Docker
  hosts: localhost
  become: true
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    docker_gpg_key_url: "https://download.docker.com/linux/ubuntu/gpg"
    docker_repo: "deb https://download.docker.com/linux/ubuntu focal stable"

  tasks:
    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: "{{ docker_gpg_key_url }}"
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: "{{ docker_repo }}"
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker CE
      ansible.builtin.apt:
        name: docker-ce
        state: latest

    - name: Install Docker Compose Plugin
      ansible.builtin.apt:
        name: docker-compose-plugin
        state: latest

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Enable and start Docker services
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started
