remote_servers:
  hosts:
    server1:
      ansible_host: 12.34.56.78 # IP address of the remote server
      ansible_user: root # User to be used for SSH connection
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519 # Private key to be used for SSH connection
      new_user: ubuntu # New user to be created
      pub_key_file: ~/.ssh/id_ed25519.pub # Public key to be added to the new user's authorized_keys file