- name: Prepare Ubuntu Desktop
  hosts: localhost
  become: yes
  tasks:

    # set the user variable to the current user
    - name: Set the user
      become: false
      set_fact: user="{{ lookup('env','USER') }}"

    - name: Updates the apt cache
      apt:
        update_cache: yes


    - name: Add apt repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - ppa:hluk/copyq


    # install apt softwares using loop
    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - wget
        - git
        - zsh
        - htop
        - docker.io
        - flameshot
        - firefox
        - libreoffice
        - copyq

    # install snap softwares using loop
    - name: Install snap packages
      snap:
        name: "{{ item }}"
        state: present
      loop:
        - code
        - discord
        - postman
        - slack
        - spotify
        - telegram-desktop

    - name: Download the warp.deb file
      get_url:
        url: "https://releases.warp.dev/stable/v0.2024.04.23.08.01.stable_03/warp-terminal_0.2024.04.23.08.01.stable.03_amd64.deb"
        dest: /tmp/warp.deb

    - name: Install the warp.deb file
      apt:
        deb: /tmp/warp.deb
        state: present

    - name: Add the user to the docker group to run docker without sudo
      user:
        name: "{{ user }}"
        groups: docker
        append: yes

    - name: Apply the changes
      command: newgrp docker

    - name: Check if Docker runs without sudo
      become: no
      register: docker_output
      command: docker run hello-world
      ignore_errors: yes

    - name: Verificar se o comando foi bem-sucedido
      debug:
        msg: "O comando docker run hello-world foi executado com sucesso."
      when: docker_output.rc == 0

    - name: Exibir saída do comando em caso de erro
      debug:
        msg: "Erro ao executar o comando docker run hello-world: {{ docker_output.stdout }}"
      when: docker_output.rc != 0

    - name: Instalar NVM (Permitem instalar várias versões do Node.js)
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash