- name: Prepare Ubuntu Desktop
  hosts: localhost
  become: true

  tasks:

    - name: Add apt repositories
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - ppa:hluk/copyq

    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

    - name: Install apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - wget
        - gdebi
        - git
        - zsh
        - htop
        - flameshot
        - firefox
        - libreoffice
        - copyq

    - name: Install snap packages
      ansible.builtin.snap:
        name: "{{ item }}"
        state: present
      loop:
        - code
        - discord
        - postman
        - slack
        - spotify
        - telegram-desktop

    - name: Download the warp.deb file
      ansible.builtin.get_url:
        url: "https://releases.warp.dev/stable/v0.2024.04.23.08.01.stable_03/warp-terminal_0.2024.04.23.08.01.stable.03_amd64.deb"
        dest: /tmp/warp.deb

    - name: Install the warp.deb file
      ansible.builtin.apt:
        deb: /tmp/warp.deb
        state: present
