---
- name: Creates new Users with Home Directory and sudo group
  hosts: localhost
  become: true
  vars:
    user: silvioney
    password: silvioney

  tasks:
    - name: Creates new group
      ansible.builtin.group:
        name: "{{ user }}"
        state: present

    - name: Creates a new user
      ansible.builtin.user:
          name: "{{ user }}"
          password: "{{ password | password_hash('sha512') }}"
          shell: /bin/bash
          home: /home/{{ user }}
          createhome: yes
          state: present
          groups: "{{ user }}, sudo"
          append: yes

    - name: Set home directory permissions
      ansible.builtin.file:
        path: /home/{{ user }}
        state: directory
        recurse: yes
        mode: 0755
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Creates the .ssh folder
      ansible.builtin.file:
        path: /home/{{ user }}/.ssh
        state: directory
        mode: 0700
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Creates the authorized_keys file
      ansible.builtin.file:
        path: /home/{{ user }}/.ssh/authorized_keys
        state: touch
        mode: 0600
        owner: "{{ user }}"
        group: "{{ user }}"